# Generated by Django 4.0.4 on 2022-04-27 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_music'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Music',
        ),
    ]
